env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
  react/react-in-jsx-scope: 0
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
  react/prop-types: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
  no-console: 0
